# Google sheet -> Intranet employee list
Office_location = {
    "SHG": "SHG",
    "HKG": "HKG",
    "MUM": "DEL",
    "LDN": "LDN",
    "NYC": "NYC",
    "BEJ": "SHG"
}

Role = {
    "N/A": "",
    "Intern": "INTERN",
    "Associate": "RESEARCH_ANALYST_LVL1",
    "Client Associate": "RESEARCH_ASSOCIATE",
    "Senior Associate": "SENIOR_RESEARCH_ASSOCIATE",
    "Team Leader": "TEAM_LEADER",
    "Team Leader, Research Operations" : "TEAM_LEADER"
}

Team = {
    "Con - Kun": "59",
    "Con - Qian": "58",
    "Con - Tai": "126",
    "Con - Xian": "147",
    "PE - Dui": "107",
    "PE - Kan": "35",
    "PE - Li": "36",
    "PE - Ze": "146",
    "HF - Yi" : "175",
    "HF - Zhen": "51",
    "Sapporo": "182",
    "Alpha": "181",
    "Universe": "180",
    "Research Coordinators": "63",
    "HK - Operation": "63",
    "HK - Bluebell": "155",
    "HK - Bauhinia": "104",
    "HK - Plumeria": "103",
    "HK - Rafflesia": "102",
    "Finance": "16",
    "Forum": "19",
    "HK Sales": "18",
    "HR": "14",
    "Maurya": "11",
    "Indus": "91",
    "IT": "13",
    "Legal": "15",
    "Marketing": "22",
    "Account Management": "85",
    "Sales-AM": "85",
    "Sales": "18",
    "Property": "1",
    "Product & Innovation": "13",
    "Connections Operations" : "113",
    "Aryan" : "165"
}

Title = {
    "Account Management Associate": "Account Management Associate",
    "Account Manager": "Account Manager",
    "Account Manager, APAC": "",
    "Accountant": "Accountant",
    "Accounts Assistant": "Accounts Assistant",
    "Accounts Payable Accountant": "",
    "Accounts Payable Assistant": "",
    "Administrative Account": "Administrative account",
    "Administrative Assitant": 12,
    "Analyst": "Analyst",
    "Application Support Engineer": "Support Engineer",
    "Assistant Management Accountant": "Assistant Management Accountant",
    "Associate": "Associate",
    "Associate Counsel": "Associate Counsel",
    "Associate Brand Manager": "Associate Brand Manager",
    "Associate Management Accountant": "Associate Management Accountant",
    "AVP - Business Development": "AVP - Business Development",
    "AVP Account Management": "AVP Account Management",
    "AVP Sales": "AVP Sales",
    "BI Developer": "BI Developer",
    "Business Analyst": "Business Analyst",
    "Business Development Analyst": "Business Development Analyst",
    "Business Development Associate": "Business Development Associate",
    "Business Development Manager": "Business Development Manager",
    "Campus Recruiter": "Campus Recruiter",
    "Campus Recruitment Coordinator": "Campus Recruitment Coordinator",
    "Chairman": "Chairman",
    "Chief Executive Officer": "Chief Executive Officer",
    "Chief Financial Officer": "Chief Financial Officer",
    "Chief Operating Officer": "Chief Operating Officer",
    "Client Manager": "Client Manager",
    "Compliance Assistant": "Compliance Assistant",
    "Consultant": "Consultant",
    "Content Coordinator": "",
    "Content Manager": "Content Manager",
    "Country Head, China": "Country Head, China",
    "Credit Control Assistant": "Credit Control Assistant",
    "Credit Controller": "Credit Controller",
    "CTO": "CTO",
    "Data Analyst": "Data Analyst",
    "Desktop Support Engineer": "Desktop Support Engineer",
    "Developer": "Developer",
    "Development Deployment Manager": "Development Deployment Manager",
    "DevOps Engineer": "DevOps Engineer",
    "Digital Analyst": "Digital Analyst",
    "Digital Project Coordinator": "Digital Project Coordinator",
    "Director": "Director",
    "Director, Asia Operations": "Director, Asia Operations",
    "Events Analyst": "",
    "Events Associate": "Events Associate",
    "Events Manager": "Events Manager",
    "Executive Assistant": "Executive Assistant",
    "Finance Administrator": "Finance Administrator",
    "Finance Associate": "Finance Associate",
    "Finance Contractor": "Finance Contractor",
    "Finance Operations Manager": "Finance Operations Manager",
    "Finance Temp": "Finance Temp",
    "Financial Controller": "Financial Controller",
    "Financial Director": "Financial Director",
    "Forum Analyst": "Forum Analyst",
    "Forum Operations Intern": "Forum Operations Intern",
    "Global Head of Client Services": "Global Head of Client Services",
    "Global Head of Infrastructure": "Global Head of Infrastructure",
    "Global Head of IT Systems": "Global Head of IT Systems",
    "Global Head of Product Development": "Global Head of Product Development",
    "Global Head of Talent": "Global Head of Talent",
    "Global Training and Development Leader": "Global Training and Development Leader",
    "Head of Business Development, Europe": "",
    "Head of Greater China": "Head of Greater China",
    "Head of India": "Head of India",
    "Head of Marketing": "",
    "Head of Operations": "Head of Operations",
    "Head of Product Experience": "Head of Product Experience",
    "Head of Quality Assurance": "Head of Quality Assurance",
    "Head of Sales, China": "",
    "Head of Software Development": "Head of Software Development",
    "Head of Technology Solutions": "Head of Technology Solutions",
    "Head of Account Management,China" : "Head of Account Management, China",
    "HR & Recruitment Assistant": "HR & Recruitment Assistant",
    "HR Business Partner": "HR Business Partner",
    "HR Coordinator": "HR Coordinator",
    "HR Generalist": "HR Generalist/Business Partner",
    "HR Specialist": "HR Specialist",
    "Human Resources": "Human Resources",
    "Interim Head of Finance": "Interim Head of Finance",
    "Intern": "Intern",
    "Internal Recruiter": "Internal Recruiter",
    "Junior Editor": "Junior Editor",
    "Junior Legal & Compliance Assistant": "",
    "Lead Developer": "Lead Developer",
    "Lead Project Manager": "Lead Project Manager",
    "Learning and Development Manager": "Learning and Development Manager",
    "Legal & Compliance": "Legal & Compliance",
    "Legal & Compliance Advisor": "Legal & Compliance Advisor",
    "Legal & Compliance Assistant": "Legal & Compliance Assistant",
    "Legal & Compliance Associate": "Legal & Compliance Associate",
    "Legal and Compliance Supervisor": "Legal and Compliance Supervisor",
    "Legal Team Administrator": "Legal Team Administrator",
    "Management Accountant": "Management Accountant",
    "Manager": "Manager",
    "Managing Director": "Managing Director",
    "Marketing & Communications Assistant": "",
    "Marketing & Communications Manager": "",
    "Marketing Analyst": "Marketing Analyst",
    "Marketing Assistant": "",
    "Marketing Associate": "Marketing Associate",
    "MD, Business Development": "MD, Business Development",
    "Moderator Analyst": "Analyst - Moderator",
    "Moderator Associate": "Associate - Moderator",
    "Moderator Senior Associate": "Senior Associate - Moderator",
    "Office & Facilities Coordinator": "Office & Facilities Coordinator",
    "Office & Facilities Manager": "Office & Facilities Manager",
    "Office Administrator": "Office Administrator",
    "Office Administrator (Contractor)": "Office Administrator (Contractor)",
    "Office Assistant": "Office Assistant",
    "Office Manager": "Office Manager",
    "Office Manager (Contractor)": "Office Manager (Contractor)",
    "Operational Quality Leader": "Operational Quality Leader",
    "Operations Analyst": "Operations Analyst",
    "Operations Coordinator": "Operations Coordinator",
    "Operations Manager": "Operations Manager",
    "Payroll & Immigration Specialist": "Payroll & Immigration Specialist",
    "Personal Assistant": "Personal Assistant",
    "Process Manager": "Process Manager",
    "Product Manager": "Product Manager",
    "Product Operation Manager": "Product Operation Manager",
    "Product Owner": "Product Owner",
    "Project Coordinator": "Project Coordinator",
    "Project Manager": "Project Manager",
    "Purchase Ledger Assistant": "Purchase Ledger Assistant",
    "QA Analyst": "QA Analyst",
    "QA Manager": "QA Manager",
    "Receptionist": "Receptionist",
    "Recruiter": "Recruiter",
    "Recruitment Coordinator": "Recruitment Coordinator",
    "Recruitment Manager": "Recruitment Manager",
    "Recruitment Specialist": "Recruitment Specialist",
    "Regional Team Leader": "Regional Team Leader",
    "Research Associate": "Research Associate",
    "Research Coordination Manager": "",
    "Research Coordinator": "Research Coordinator",
    "Research Manager": "Research Manager",
    "Researcher": "Researcher",
    "Sales Associate": "Sales Associate",
    "Sales Representative": "Sales Representative",
    "Senior Account Associate": "",
    "Senior Account Management Associate": "Senior Associate - Account Management",
    "Senior AM Associate": "Senior AM Associate",
    "Senior Associate": "Senior Associate",
    "Senior Associate, Sales": "Senior Associate, Sales",
    "Senior BI & Data Engineer": "Senior BI & Data Engineer",
    "Senior Developer": "Senior Developer",
    "Senior Financial Analyst": "Senior Financial Analyst",
    "Senior Front-End Developer": "Senior Front-End Developer",
    "Senior Recruiter": "Senior Recruiter",
    "Senior Research Associate": "Senior Research Associate",
    "Senior Research Coordinator": "Senior Research Coordinator",
    "Senior Research Executive": "Senior Research Executive",
    "Senior Server Side Developer": "Senior Server Side Developer",
    "Senior Systems Engineer": "Senior Systems Engineer",
    "Senior Manager" : "Senior Manager",
    "Senior Systems Manager": "Senior Systems Manager",
    "Senior Vice President": "Senior Vice President",
    "Senior VP Sales": "Senior VP Sales",
    "Server Side Developer": "Server Side Developer",
    "Software Engineer": "Software Engineer",
    "Sub Editor": "Sub-Editor",
    "Support Engineer": "Support Engineer",
    "System Administrator": "System Administrator",
    "Talent Recruiter": "Talent Recruiter",
    "Team Leader": "Team Leader",
    "Team Leader, Research Operations": "Team Leader, Research Operations",
    "Technical Director": "Technical Director",
    "Technical Lead": "Technical Lead",
    "Technology Solutions Manager": "Technology Solutions Manager",
    "Thirdbridge": "Thirdbridge",
    "User Experience Architect": "User Experience Architect",
    "Vice President - North America": "Vice President - North America",
    "Vice President Sales": "Vice President Sales",
    "Vice President, Business Development": "Vice President, Business Development",
    "VP": "VP",
    "VP Account Management": "VP Account Management",
    "VP Business Improvement": "VP Business Improvement",
    "VP Forum": "VP Forum",
    "VP of Operations": "VP of Operations",
    "VP of Research": "VP of Research",
    "VP of Software Engineering": "VP of Software Engineering",
    "VP Operations": "VP Operations",
    "VP Operations Project Management": "VP Operations Project Management",
    "VP Operations, Korean and Japanese": "VP Operations, Korean and Japanese",
    "VP Product Management": "",
    "VP Sales": "VP Sales",
    "VP Sales, Asia": "VP Sales, Asia",
    "VP Sales, Europe": "VP Sales, Europe",
    "VP Strategy & Product Development": "",
    "VP Talent Acquisition": "VP Talent Acquisition",
    "SVP" : "SVP"

}

position = ['11', '16', '23', '35', '36', '40', '42', '43', '44', '45', '51', '54', '58', '59', '60', '62', '64', '70',
            '71', '73', '76', '89', '91', '96', '98', '100', '101', '102', '103', '104', '107', '111', '114', '115',
            '119', '120', '126', '128', '130', '131', '135', '138', '146', '147', '148','155', '159', '160', '161',
            '162', '163', '165', '166', '167', '168', '169', '170', '171', '172']


Language = {
    "SHG": "zh-cmn",
    "HKG": "en",
    "MUM": "en",
    "LDN": "en",
    "NYC": "en",
    "BEJ": "zh-cmn"
}




